### ISSUE TITLE
Is it possible to port this to browser?

### ISSUE THREAD

**Issue by anurbol** [keymetrics/event-loop-inspector#2]
Great lib. You use _getActiveHandles, which is Node's thing. Do you think it is possible to enhance the lib to use in browsers?

**Comment by wallet77** [comment]
Hi @anurbol 

Indeed we use : 
- _getActiveHandles
- _getActiveRequests
- patch on setImmediate

So we can't use it into browser. Even the patch on setTimeout I'm not sure it can work "as is" in the browser.

The idea is interesting but I think we should create another project for this because the event loop in nodejs is not the same event loop in the browser.

**Comment by anurbol** [comment]
Oh, ok. Just was curious. It could help with performance in browser. Thank you for answer!
